"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Main.py']
DATA_FILES = [
    'Fonts',
    'Images',
    'Shaders',
    'Sounds',
    'Settings.json',
    ('Scripts/hifigan', ['Scripts/hifigan/config.json']),
]
OPTIONS = {
    'iconfile': 'Images/Icon.png',
    'packages': ['sounddevice', 'unidecode', 'inflect', 'scipy'],
    'includes': ['pygame', 'moderngl', 'numpy', 'ollama', 'gdown', 'sounddevice', 'matplotlib', 'librosa', 'scipy', 'unidecode', 'inflect', 'torch', 'torchvision'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
